### ISSUE TITLE
No support for arm64

### ISSUE THREAD

**Issue by multiplemonomials** [pelya/libiconv-libicu-android#4]
With the growth of arm64/aarch64 devices, people need to be able to build these libraries for those architectures as well.

I made a [cross tools script](https://github.com/pelya/libiconv-libicu-android/files/908487/setCrossEnvironment-arm64-v8a.sh.zip) that works for me (with a bit of cajoling) for arm64, but it is not 100% tested and working.

**Comment by multiplemonomials** [comment]
Oh, if people want it, I ran a full build of both libraries for all 5 architectures.  You can download it [here](https://app.box.com/shared/static/fusshg6kdgcryg6ekovyo3udy1rpo9t2.7z).  It uses `gnustl_shared` for the c++ library, so make sure to set that in your build systems.

**Comment by pelya** [comment]
Nice. If you make a merge request I'll merge that.

**Comment by pelya** [comment]
Fixed
